import {
  Binary,
  GitBranch,
  Network,
  Cpu,
  Database,
  Layers,
  Bug,
  Terminal,
  BarChart3,
  MessageSquare,
  Zap,
  Play,
  Pause,
  RotateCcw,
  SkipForward,
  SkipBack,
  Search,
  Settings,
  Sun,
  Moon,
  User,
  Lock,
  Eye,
  EyeOff,
  Check,
  Globe,
  BookOpen,
  Activity,
  ShieldCheck,
  Code2,
  Sparkles,
  ChevronRight,
  ChevronLeft,
  X,
  Server,
  HardDrive,
  Box,
  LucideProps,
} from 'lucide-react';
import React from 'react';

export const iconMap: Record<string, React.FC<LucideProps>> = {
  // CS Domains & Topics
  binary: Binary,
  gitBranch: GitBranch,
  network: Network,
  cpu: Cpu,
  database: Database,
  layers: Layers,
  bug: Bug,
  terminal: Terminal,
  barChart: BarChart3,
  messageSquare: MessageSquare,
  zap: Zap,
  code: Code2,
  server: Server,
  hardDrive: HardDrive,
  box: Box,

  // Player Controls
  play: Play,
  pause: Pause,
  rotateCcw: RotateCcw,
  stepForward: SkipForward,
  stepBack: SkipBack,

  // UI Navigation & Controls
  search: Search,
  settings: Settings,
  sun: Sun,
  moon: Moon,
  user: User,
  lock: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  check: Check,
  globe: Globe,
  bookOpen: BookOpen,
  activity: Activity,
  shieldCheck: ShieldCheck,
  sparkles: Sparkles,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  close: X,
};

export const featureIconMap: Record<string, string> = {
  dsa: 'binary',
  algorithms: 'gitBranch',
  networking: 'network',
  operatingSystems: 'cpu',
  databases: 'database',
  systemDesign: 'layers',
  debugging: 'bug',
  coding: 'terminal',
  analytics: 'barChart',
  interview: 'messageSquare',
  visualizer: 'zap',
  courses: 'bookOpen',
  practice: 'code',
  api: 'server',
};

export type IconName = keyof typeof iconMap;
export type FeatureName = keyof typeof featureIconMap;
